# Generated by Django 5.2.6 on 2025-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historycheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycheckorderitem',
            name='history_text',
            field=models.TextField(default=''),
        ),
    ]
