# Generated by Django 5.2.6 on 2025-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historycheck', '0002_historycheckorderitem_history_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historycheckorderitem',
            name='history_text',
        ),
        migrations.AddField(
            model_name='historycheckorder',
            name='history_text',
            field=models.TextField(default=''),
        ),
    ]
